version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    target-branch: development
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "UTC"
    labels:
      - dependencies
      - security
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: development
        patterns:
          - "*"
