import { isContentDuplicate } from '../src/utils/contentDeduplication';
import * as fs from 'fs';
import * as path from 'path';

const logFile = path.join(process.cwd(), 'posted-outputs.log');
if (!fs.existsSync(logFile)) {
  console.error('posted-outputs.log not found');
  process.exit(1);
}

const testCases = [
  'Life was strange: color two weeks ago', // Should be duplicate
  'I have a big man!', // Should be duplicate
  'Something completely new', // Should NOT be duplicate
  'CENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENTCENT!', // Should be flagged as spam/duplicate
];

for (const test of testCases) {
  const result = isContentDuplicate(test);
  console.log(`Test: "${test.slice(0, 60)}..."\n  Duplicate?`, result);
}
